#!/usr/bin/env bash

# At submision time, this script is located at `~/lake-packages/autograder/run_autograder_main`.
# The `run_autograder` script is expected to copy it to `~`.
# It is run in `~`.

set -ex

cp config.json lake-packages/autograder/autograder_config.json

cp /autograder/submission/* Assignment.lean

cd lake-packages/autograder/PythonScripts

python3 get_template_from_github.py

cd ../../..

~/.elan/bin/lake exe cache get 

if ! ~/.elan/bin/lake build autograder AutograderTests ; then 
  cp bad_autograder_error.json ../results/results.json 
  exit 1
fi
  
cp Assignment.lean lake-packages/autograder/AutograderTests/Assignment.lean 

if ! ~/.elan/bin/lake build autograder AutograderTests ; then 
  cp fails_to_compile_error.json ../results/results.json 
  exit 1
fi

~/.elan/bin/lake exe autograder AutograderTests.Solution Assignment.lean
