#!/usr/bin/env bash

# At submision time, this script is located at `~/lake-packages/autograder/run_autograder_main`.
# The `run_autograder` script is expected to copy it to `~`.
# It is run in `~`.

set -ex

cp config.json lake-packages/autograder/autograder_config.json

cp /autograder/submission/* Assignment.lean

~/.elan/bin/lake exe cache get

~/.elan/bin/lake exe autograder Assignment.lean
